### ISSUE TITLE
Register & invoke computer services (OEP-6)

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/OEPs#12]
This OEP should provide the following information:
- [ ] What we want to accomplish invoking computer services
- [ ] What is a Workflow Management System
- [ ] How can be defined a workflow (the whole workflow, sources, sinks, stages, etc.)
- [ ] Workflow topologies
- [ ] How a workflow can integrate Ocean Assets (Datasets & Algorithms) to compose a complete execution pipeline
- [ ] Scheduling
- [ ] Runtime scopes, where is executed the workflow scheduling and where is executed the workflow stages
- [ ] What information need to be registered on-chain?
- [ ] Workflow registration (High Level APIs)

**Comment by aabdulwahed** [comment]
https://github.com/oceanprotocol/OEPs/tree/feature/OEP-06_invoke_services

**Comment by aaitor** [comment]
@aabdulwahed , I think we can re-use this for the upcoming integration of runtime engines (Truebit,..)

**Comment by aabdulwahed** [comment]
@aaitor totally agree

**Comment by H34D** [comment]
https://github.com/oceanprotocol/OEPs/pull/36

**Comment by ttmc** [comment]
I think this issue is being tackled by OEP-12, which is currently being developed in pull request #162.

**Comment by kremalicious** [comment]
Superseded by OEP-12 https://github.com/oceanprotocol/OEPs/tree/master/12
