### ISSUE TITLE
Proposal: HashLockCondition

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/OEPs#120]
```
shortname: <TBA>
name: HashLockCondition
type: Standard
status: Proposal
editors: Dimitri De Jonghe <dimi@oceanprotocol.com>
```

# HashLockCondition

This document describes the Ocean's HashLockCondition that can be used in the modular Service Execution Agreements (SEA), [see OEP/SEA](https://github.com/oceanprotocol/OEPs/tree/master/11).
Functions, components and implementation details are layed out here.

## Change Process
This document is governed by the [2/COSS](../2/README.md) (COSS).

## Language
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) \[[RFC2119](https://tools.ietf.org/html/rfc2119)\] \[[RFC8174](https://tools.ietf.org/html/rfc8174)\] when, and only when, they appear in all capitals, as shown here.

## Motivation

Find a pre-image that computes to a given hash. The computation of the hash of the pre-image happens on-chain. This condition is useful for a party to prove that they have knowledge of a secret. 

By default the HashLockCondition uses the `keccak256` hashing function.

This specification serves as a simple implementation of `Condition`

More information on Conditions and ConditionStore can be found in #119.

## Design Requirements

- inherit requirements from #119 

## Specification

**NOTES**:
 - The following specifications use syntax from Solidity `0.4.22` (or above)

## HashLockCondition

![image](https://user-images.githubusercontent.com/6178597/50963076-03bb4800-14cc-11e9-951f-65147424978b.png)

### Contract

HashLockCondition MUST inherit from `Condition` see #119 ##Condition.

``` js
contract HashLockCondition is Condition
```

#### Constructor

Upon contract deployment, the HashLockCondition MUST instantiate the `ConditionStore`, deployed at 
`conditionStoreAddress`.

``` js
constructor(address conditionStoreAddress) public 
```

#### ConditionStore

Storage contract to store conditions, see #119 ##ConditionStore.

``` js
ConditionStore internal conditionStore;
```

#### create

Create a new `HashLockCondition` with state `ConditionState.Unfufilled`.
`hash` is the hash of the preimage to fulfill this condition.

**NOTE**: The id of `conditionStore` MUST be generated using `generateId(agreementId, hash)`.

``` js
function create(bytes32 agreementId, bytes32 hash) public returns (bool)
```

#### fulfill

Validate an initialized `HashLockCondition` which MAY update the state to  `ConditionState.Fufilled`. The fulfill method SHALL only change state of a condition identified by `generateId` that encodes the `condition` instance.

**NOTE**: `agreementId` and `hashValues(preimage)`  are used to find the `id` of the condition in ConditionStore, see ####generateId. 
    
``` js
function fulfill(bytes32 agreementId, uint256 preimage) public returns (bool)
```

``` js
function fulfill(bytes32 agreementId, string memory preimage) public returns (bool)
```

``` js
function fulfill(bytes32 agreementId, bytes32 preimage) public returns (bool)
```

``` js
function fulfill(bytes32 agreementId, bytes memory preimage) public returns (bool)
```

#### generateId

Inherited from `Condition`, see #119 ####generateId

**NOTE** Makes use of `hashValues()`

#### hashValues

Hashes `preimage` using the `keccak256` hashing algorithm. 

OPTIONAL - This method can be used to improve usability (eg. `generateId`) , but interfaces and other contracts MUST NOT expect these values to be present.

``` js
function hashValues(uint256 preimage) public pure returns (bytes32)
```

``` js
function hashValues(string memory preimage) public pure returns (bytes32)
```

``` js
function hashValues(bytes32 preimage) public pure returns (bytes32)
```

``` js
function hashValues(bytes memory preimage) public pure returns (bytes32)
```
#### ConditionCreated

MUST trigger when a new HashLockCondition is created.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionCreated(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

#### ConditionFulfilled

MUST trigger when a new HashLockCondition changes state to `ConditionState.Fulfilled`.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionFulfilled(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

**Comment by aabdulwahed** [comment]
Looks clean and short. 

- Correct me If I am wrong: `HashCondition` looks similar to [hash locks](https://en.bitcoin.it/wiki/Hashlock) ? If so, it would be easier to change the name of the contract to `HashLockCondition`.
- hash condition functions such as `hashValues, create, and fulfil/validate` look more to be defined in terms of`Abstract` or `Interface` , because the `args or preimage` could vary from use case to another. The contract which inherits `hashCondition` should have the ability overrides these args.

**Comment by diminator** [comment]
> * Correct me If I am wrong: `HashCondition` looks similar to [hash locks](https://en.bitcoin.it/wiki/Hashlock) ? If so, it would be easier to change the name of the contract to `HashLockCondition`

:+1:

**Comment by diminator** [comment]
> * `Abstract` or `Interface` , because the `args or preimage` could vary from use case to another. The contract which inherits `hashCondition` should have the ability overrides these args.

tried it, but then the interface would require to implement every combination of arguments of every condition type (hashlock, signature, lockreward, ...), which seems unfeasible

**Comment by trentmc** [comment]
Obsolete. Closing.
