### ISSUE TITLE
Proposal: SignCondition

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/OEPs#121]
```
shortname: <TBA>
name: SignCondition
type: Standard
status: Proposal
editors: Dimitri De Jonghe <dimi@oceanprotocol.com>
```

# SignCondition

This document describes the Ocean's SignCondition that can be used in the modular Service Execution Agreements (SEA), [see OEP/SEA](https://github.com/oceanprotocol/OEPs/tree/master/11).
Functions, components and implementation details are layed out here.

## Change Process
This document is governed by the [2/COSS](../2/README.md) (COSS).

## Language
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) \[[RFC2119](https://tools.ietf.org/html/rfc2119)\] \[[RFC8174](https://tools.ietf.org/html/rfc8174)\] when, and only when, they appear in all capitals, as shown here.

## Motivation

Sign a given message with a private key corresponding to a given public key. The verification of the signature happens on-chain. Useful to prove an identity in an asymmetric key pair scheme.

By default the SignCondition uses the `ECDSA` recover function from OpenZeppelin (see [link](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/cryptography/ECDSA.sol)).

This specification serves as a simple implementation of `Condition`

More information on Conditions and ConditionStore can be found in #119.

## Design Requirements

- inherit requirements from #119 

## Specification

**NOTES**:
 - The following specifications use syntax from Solidity `0.4.22` (or above)

## SignCondition

![image](https://user-images.githubusercontent.com/6178597/50965990-e7230e00-14d3-11e9-825b-9263d295f75a.png)

### Contract

SignCondition MUST inherit from `Condition` see #119 ##Condition.

``` js
contract SignCondition is Condition
```

#### Constructor

Upon contract deployment, the SignCondition MUST instantiate the `ConditionStore`, deployed at 
`conditionStoreAddress`.

``` js
constructor(address conditionStoreAddress) public 
```

#### ConditionStore

Storage contract to store conditions, see #119 ##ConditionStore.

``` js
ConditionStore internal conditionStore;
```

#### create

Create a new `SignCondition` with state `ConditionState.Unfufilled`.
`message` is the message to sign and `publicKey` is the address of the signer.

**NOTE**: The id of `conditionStore` MUST be generated using `generateId(agreementId, hashValues(agreementId, message, publicKey))`.

``` js
function create(bytes32 agreementId, bytes32 message, address publicKey) public returns (bool)
```
``` js
function create(bytes32 agreementId, bytes memory message, address publicKey) public returns (bool)
```
``` js
function create(bytes32 agreementId, string memory message, address publicKey) public returns (bool)
```

#### fulfill

Validate an initialized `SignCondition` which MAY update the state to  `ConditionState.Fufilled`. The fulfill method SHALL only change state of a condition identified by `generateId` that encodes the `condition` instance.

**NOTE**: `agreementId` and `hashValues(message, address)` are used to find the `id` of the condition in ConditionStore. `signature` is excluded from the `id`. See ####generateId.
    
``` js
function fulfill(bytes32 agreementId, bytes32 message, address publicKey, bytes memory signature) public returns (bool)
```
``` js
function fulfill(bytes32 agreementId, bytes memory message, address publicKey, bytes memory signature) public returns (bool)
```
``` js
function fulfill(bytes32 agreementId, string memory message, address publicKey, bytes memory signature) public returns (bool)
```

#### generateId

Inherited from `Condition`, see #119 ####generateId

**NOTE** Makes use of `hashValues()`

#### hashValues

Combines `message` and `publicKey` and hashes the result using the `keccak256` hashing algorithm. 

OPTIONAL - This method can be used to improve usability (eg. `generateId`) , but interfaces and other contracts MUST NOT expect these values to be present.

``` js
function hashValues(bytes32 message, address publicKey) public pure returns (bytes32)
```

``` js
function hashValues(bytes memory message, address publicKey) public pure returns (bytes32)
```

``` js
function hashValues(string memory message, address publicKey) public pure returns (bytes32)
```
#### ConditionCreated

MUST trigger when a new SignCondition is created.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionCreated(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

#### ConditionFulfilled

MUST trigger when a new SignCondition changes state to `ConditionState.Fulfilled`.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionFulfilled(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

**Comment by trentmc** [comment]
Obsolete. Closing.
