### ISSUE TITLE
Proposal: Modular Service Execution Agreements

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/OEPs#125]
```
shortname: <TBA>
name: Modular Service Execution Agreements
type: Standard
status: Proposal
editors: Dimitri De Jonghe <dimi@oceanprotocol.com>
```

# Modular Service Execution Agreements

This document describes the specification of the modular Service Execution Agreements (SEA), [see OEP/SEA](https://github.com/oceanprotocol/OEPs/tree/master/11).
Functions, components and implementation details are laid out here.

## Change Process
This document is governed by the [2/COSS](../2/README.md) (COSS).

## Language
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) \[[RFC2119](https://tools.ietf.org/html/rfc2119)\] \[[RFC8174](https://tools.ietf.org/html/rfc8174)\] when, and only when, they appear in all capitals, as shown here.

## Motivation

In the Ocean Network we care about data and AI services being fairly exchanged, protecting all ends of the business transaction. This way terms and conditions of a service agreement are known upfront without relying on an external party for dispute inter-mediation. Service Agreements and their life cycle form the basis for:

- Decentralized access control
- Dispute resolution
- Provenance of service consumption
- Network rewards and incentives

![image](https://user-images.githubusercontent.com/6178597/51538429-87bcea80-1e51-11e9-982d-cb178a54d731.png)

In Ocean Protocol, SEAs have a modular design to encompass flexibility for on-boarding and consuming a variety of web2.0 (cloud/on-premise) and web3.0 services.

We identify three main parts in a SEA:

![image](https://user-images.githubusercontent.com/6178597/51185120-9564f400-18d6-11e9-97ef-aa0c50ea8490.png)

### Service Identifier

A cryptographic ID that uniquely identifies the service to be consumed. The actual metadata and endpoint/access details of the service are kept off-chain for both scale and privacy reasons.

For more information see:
- The service identifier: [OEP7/DID](https://github.com/oceanprotocol/OEPs/tree/master/7)
- The service metadata: [OEP8/DDO](https://github.com/oceanprotocol/OEPs/tree/master/7)

### Service Conditions

A module for service integrity challenges and proofs. Conditions can be regarded as the inputs to a SEA. For more information see: #119 

### Reward Logic

The outputs of a SEA are rewards that are typically distributed to agents that have fulfilled one or more conditions. Rewards can be issued in the form of payments, royalties, permissions, badges, reputation or lottery tickets for a network reward function, and so on. 

For more information see: **#TODO-Reward**

### Life cycle of an agreement

Depending on the type of SEA, the order of condition and reward events will differ. The specification foresees a convenient approach to schedule the order and precedence of events.

![image](https://user-images.githubusercontent.com/6178597/51561729-48f65700-1e88-11e9-9a6d-bb9e6583bee7.png)

More information can be found in [this blogpost](https://blog.oceanprotocol.com/exploring-the-sea-service-execution-agreements-65f7523d85e2).

## Design Requirements

- Storage
  - Agreements MUST be stored in an AgreementStore (see below)
  - Templates MUST be stored in a TemplateStore (#132)
  - Conditions & Rewards MUST be stored in a ConditionStore (#119)
- Modularity
  - SEAs MUST support generic Conditions through the abstract interface, as specified in #119.
  - SEAs MUST support generic Rewards through the abstract interface, as specified in #TODO-Reward.
  - SEAs MUST support instantiation of timeouts and possibly other attributes of Conditions (dependencies and ), as specified in #TODOs-Deps.
  - SEAs MUST support the instantiation of Conditions and Rewards per Template specification, see #132
- Upgradeability:
  - New condition or reward types that are deployed after the SEA contract MUST be supported without storage contract re-deployment.
- Security:
  - Only the SEA logic is able to create new Conditions and Rewards in the ConditionStore. This avoids referencing conditions cross-agreement. In the future, it should be possible for Agreements to reference other agreements as condition inputs.
  - Access to Storage functions must be guarded and validated per instance type.
- Integrity:
  - Each SEA has a unique ID and can only be used once.

## Specification

**NOTES**:
 - The following specifications use syntax from Solidity `0.4.25` (or above)

## AgreementStore

Class that implements the AgreementStore and the Storage logic. Connects to `ConditionStore` and `TemplateStore`.

![image](https://user-images.githubusercontent.com/6178597/51848218-7a09d800-231d-11e9-9ef3-f13d2df1bea5.png)

#### Constructor

Upon contract deployment, the `Agreement` MUST instantiate:
-  the `ConditionStore`, deployed at `conditionStoreAddress`.
-  the `TemplateStore`, deployed at `templateStoreAddress`.

``` js
constructor(address conditionStoreAddress, address templateStoreAddress) public 
```

#### Agreement

The Agreement stores: 
- a DID, stored in off-chain Metadata Storage.
- a `templateId` pointer to the TemplateStore.
- `conditionIds` and `rewardIds` in the ConditionStore.

``` js
struct Agreement {
    bytes32 did;
    bytes32 templateId;
    bytes32[] conditionIds;
    bytes32[] rewardIds;
}

mapping(bytes32 => Agreement) internal _agreements;
```

#### ConditionStore

Reference to storage contract to store conditions, see #119.

``` js
ConditionStore internal conditionStore;
```

#### TemplateStore

Reference to storage contract to store templates, see #132.

``` js
TemplateStore internal templateStore;
```

#### create

![image](https://user-images.githubusercontent.com/6178597/51895711-2219b280-23ab-11e9-8af6-39767890d50e.png)

Create a new `Agreement` according to the `Template` specified by `templateId`. This will subsequently call the `create` function of both Condition and Reward instances in the ConditionStore that defined in the `Template`.
- `agreementId` is a unique ID of the SEA that will be instantiated.
- `did` is the DID without common prefix
- `templateId` is the ID of the SEA Template that will be used for instantiation.
- `conditionIds` is a list of unique Condition IDs in the ConditionStore that are instantiated upon Agreement.
- `rewardIds` is a list of unique Reward IDs in the ConditionStore that are instantiated upon Agreement.

**NOTES**: 
- `msg.sender` is regarded as the creator of the Agreement, this can be any stakeholder in the agreement
- `conditionIds` and `rewardIds` are instantiated without performing an on-chain check on the content-addressed ID. That would require passing all attributes. It is possible to instantiate arbitrary conditions, but as `updateState` is controlled by the fulfill method, this is safeguarded. Collision IDs simply require rotation of `agreementId`. 

``` js
function create(bytes32 agreementId, bytes32 templateId, bytes32 did, bytes32[] conditionIds, bytes32[] rewardIds) public returns (bool)
```

#### AgreementCreated

MUST trigger when a new Agreement is created.

``` js
event AgreementCreated(address indexed creator, bytes32 indexed agreementId, bytes32 did)
```

**Comment by trentmc** [comment]
Obsolete. Closing.
