### ISSUE TITLE
WIP - Proposal: SEA Rewards

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/OEPs#133]
```
shortname: <TBA>
name: SEA Rewards
type: Standard
status: Proposal
editors: Dimitri De Jonghe <dimi@oceanprotocol.com>
```

# SEA Rewards

This document describes the specification of SEA Rewards.
Functions, components and implementation details are laid out here.

## Change Process
This document is governed by the [2/COSS](../2/README.md) (COSS).

## Language
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) \[[RFC2119](https://tools.ietf.org/html/rfc2119)\] \[[RFC8174](https://tools.ietf.org/html/rfc8174)\] when, and only when, they appear in all capitals, as shown here.

## Motivation

More information can be found in [this blogpost](https://blog.oceanprotocol.com/exploring-the-sea-service-execution-agreements-65f7523d85e2).

## Design Requirements

- Storage
  - Templates MUST be stored in the `TemplateStore` upon creation.
  - Templates MAY be revoked from the `TemplateStore` after a governance decision.
- Security:
  - Access to Storage functions is governed by the Template owner.
- Integrity:
  - Each Template has a unique ID and can only be used once.

## Specification

**NOTES**:
 - The following specifications use syntax from Solidity `0.4.25` (or above)

## Reward

Abstract class that implements the Reward logic. 

### Contract

Reward MUST inherit from `Condition` see #119 ##Condition.

``` js
contract Reward is Condition
```

#### Constructor

Upon contract deployment, Reward MUST instantiate the `ConditionStore`, deployed at 
`conditionStoreAddress`.

``` js
constructor(address conditionStoreAddress) public 
```

#### ConditionStore

Storage contract to store conditions, see #119 ##ConditionStore.

``` js
ConditionStore internal conditionStore;
```

#### generateId

Inherited from `Condition`, see #119 ####generateId

**NOTE** Makes use of `hashValues()`

#### ConditionCreated

MUST trigger when a new Reward is created.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionCreated(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

#### ConditionFulfilled

MUST trigger when a new Reward changes state to `ConditionState.Fulfilled`.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionFulfilled(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

#### ConditionAborted

MUST trigger when a new Reward changes state to `ConditionState.Aborted`.

**NOTE**: `conditionAddress` equals `address(this)`

``` js
event ConditionFulfilled(address indexed conditionAddress, bytes32 indexed agreementId, bytes32 id)
```

**Comment by trentmc** [comment]
Obsolete. Closing.
