### ISSUE TITLE
Update OEP8, various

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/OEPs#140]
`compression` field should be moved into`files` array, since files can have different compression
`contentType` field should be moved into`files` array, since files can have different types
`encoding` field should be moved into`files` array, since files can have different types

`links` spec is not listed in readme, but does appear in example;
```
        "links": [
            {
                "name" : "Sample of Asset Data",
                "type" : "sample",
                "url": "https://foo.com/sample.csv"
            }
        ]
```

**Comment by MarcusJones** [comment]
~~isDeleted~~ -> isListed

**Comment by ttmc** [comment]
Pull request #154 (now merged) moved the file-related metadata inside the `files` array, to that is done.

The current OEP-8 spec _does_ mention the `links` array as part of the spec, and its description says, "Mapping of links for data samples, or links to find out more information. Links may be to either a URL or another Asset. We expect marketplaces to converge on agreements of typical formats for linked data: The Ocean Protocol itself does not mandate any specific formats as these requirements are likely to be domain-specific."

I interpret that to mean that the exact structure of the `links` array members is free-form, and if there is any consistency in the examples, those shouldn't be interpreted as any kind of _de facto_ spec for what the members should look like (other than being "links" in some sense).

Therefore, in my opinion, this issue can be closed.
