### ISSUE TITLE
OEP8: Multiple contentType

### ISSUE THREAD

**Issue by Ludogil** [oceanprotocol/OEPs#151]
I've have files with different content types for the same dataset. in the OEP8 metadata design, there is only a single contentType field. How could we handle this?

**Comment by ttmc** [comment]
Issue #140 suggests one possible solution:

> `contentType` field should be moved into `files` array, since files can have different types

For now, I wouldn't worry about it too much. The current OEP-8 spec doesn't give a list of allowed or disallowed content types. You could just put "multiple" or something like that. Future versions of the spec might be more strict.

**Comment by Ludogil** [comment]
Got it! Great thank you
