### ISSUE TITLE
OEP-8: Price Type and Price Dynamics

### ISSUE THREAD

**Issue by tomthebuzz** [oceanprotocol/OEPs#164]
`
shortname: 8/ASSET-DDO 
name: Assets Metadata Ontology
type: Standard
status: Raw
version: 0.3
editor: Aitor Argomaniz <aitor@oceanprotocol.com>
contributor: Tom Debus <tom.debus@ferris.ai>
`

From our experience with curating and selling data sets and algorithms in a shared ecosystems and across a wide range of stakeholders, it would be extremely beneficial to provide more clarity and more flexibility on the *price* metadata. 

This can either be achieved by changing the price field to a more complex object or by simply extending a sub-structure like the following:

`
{
  "base": {
    "name": "10 Monkey Species Small",
    "dateCreated": "2012-02-01T10:55:11Z",    
    "author": "Mario",
    "license": "CC0: Public Domain",
    "price": 
      {
        "unitPrice": 10,
        "priceType": "updateFrequency",
        "priceTrigger": "access",
        "priceDynamics": "average"
      }
    }
    .....
}
`

Additional flavors of the three defining metadata attributes would be as follows:

priceType: oneOff, perUse, updateFrequency, qualityBased, copyLeft, revenueShare
priceTrigger: access (to the asset) or usage / consumption of the asset
priceDynamics: fixedPrice, average, rangeCap, rangeFloor, curationBased

These don‘t intend to be conclusive but simply list the most obvious once we have come across in the market data space for the Financial Services Industry.

**Comment by aaitor** [comment]
Looks good to me @tomthebuzz , we started with the simplest pricing mechanism in the definition of the OEP-8 to avoid introducing much complexity in early stages. But definitely, more complex pricing support is something we would like to have.
Your changes looks a good starting point, we will use this feedback in further refactors of this OEP.
Thanks!
