### ISSUE TITLE
Proposal: Use shortnames like OEP-2 (or OEP 2) instead of 2/COSS

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/OEPs#174]
The weird 2/COSS form actually comes from [the original COSS](https://rfc.unprotocols.org/spec:2/COSS/).

In practice (e.g. verbally), I think we tend to use the OEP-2 or "OEP 2" shortname form. The same approach is already used in the Python and Ethereum communities, e.g. [PEP 8](https://www.python.org/dev/peps/pep-0008/) and [EIP 86](https://eips.ethereum.org/EIPS/eip-86).

- Change all instances of `(number)/(name)` to `OEP-(number)` or `OEP (number)`. Including in active and likely-to-be-merged pull requests.
- Edit OEP-2, especially the sections named [OEP Format](https://github.com/oceanprotocol/OEPs/tree/master/2#oep-format) and [OEP template](https://github.com/oceanprotocol/OEPs/tree/master/2#oep-template).
- Edit the shortnames in the table in [the root README.md file](https://github.com/oceanprotocol/OEPs/blob/master/README.md).

Note that no folders or filenames need to be changed (or if any do it is not many).

**Comment by trentmc** [comment]
This change was implemented long ago. Closing.
