### ISSUE TITLE
Proposal: Put different OEP versions in different subfolders

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/OEPs#175]
When an OEP doesn't change a lot (i.e. minor or patch releases), then a new OEP is probably not necessary, but we might want to put the older versions somewhere so they are easy to find. I propose putting them in subfolders of the OEP, like for example:

`8/README.md` with links to versions/files in subfolders, and maybe some comments on status
--- `8/v0.3/README.md`
--- `8/v0.4/README.md`

If we do this, then some part of [2/COSS (OEP-2)](https://github.com/oceanprotocol/OEPs/tree/master/2) should be updated.

**Comment by kremalicious** [comment]
I think this introduces too much of a focus on old versions. With subfolders we essentially say: all those versions are on the same level and they could be all in use. And then there're all those new problems being introduced: arbitrary version numbers, defining what justifies a bump, people linking to old versions of an OEP, etc. We should always have one final version, and the rest can be linked to via git commit hashes. I feel replicating an old-school folder structure ignoring what git has to offer is just complicating things, and making updates harder. If people want to go back to an older version they'll use the version history of git.

If we want to link to older versions, we can do so at the end of an OEP, via the commit hash of former version.

**Comment by trentmc** [comment]
The actual practice to update OEPs is different than the assumption in this issue. The actual practice is simply to change the .md file for the OEP. #worksforme
