### ISSUE TITLE
Move "the SEA specs" from GitHub issues into actual OEPs (folders)?

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/OEPs#178]
Would it make sense to move "the SEA specs" from GitHub issues to actual OEPs (i.e. README.md files in numbered subfolders)? I don't remember why they were created as issues. Maybe it was some kind of experiment? I realize the specs in those issues might be out-of-date now but moving them to proper OEPs would be a first step in the right direction.

I think these are the relevant GitHub issues:

- Modular Service Execution Agreements: issue #125
- Service Conditions: issue #119
- HashLock Condition: issue #120
- Sign Condition: issue #121
- LockReward Condition: issue #122
- SEA Template Store: issue #132

**Comment by diminator** [comment]
I wanted to first iterate on them using issues and then convert them to PRs

Agreed they should be finalized and PRed

**Comment by ttmc** [comment]
I don't know enough about the current SEA implementations to finalize them, but I can move the ball forward by 1) making a pull request to move all the above-listed issues into OEP README.md files in subfolders, and 2) opening a new issue for each one, to remind us to update/finalize it.

@diminator If you would be okay with that, I will do it.

**Comment by diminator** [comment]
I'll start with it!

**Comment by trentmc** [comment]
Obsolete in light of datatokens. Closing.
