### ISSUE TITLE
No Public Glossary in Markdown format (OEP-12)

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/OEPs#19]
We don't have a public Glossary in Markdown format. Having it would be possible to provide more information to the community about the terms included in other OEP's, architecture, diagrams and so on.

By the time being exists an internal Glossary: https://docs.google.com/document/d/1KKSLnB4pgwcP0zesjDqIIXNlLAer3LT6LEK8ig6_aoc/edit?usp=sharing
It would be necessary to publish in the public space: https://github.com/oceanprotocol/ocean/wiki/Glossary

**Comment by mikera** [comment]
@timothyley can you take a crack at converting this?

**Comment by timothyley** [comment]
@mikera done

**Comment by aaitor** [comment]
Could we have it table format?
ie: https://github.com/EOSIO/eos/wiki/Glossary

I think in table format is easier to read.

**Comment by aaitor** [comment]
Glossary already published here:
https://github.com/oceanprotocol/ocean/wiki/Glossary
