### ISSUE TITLE
Rename SQUID to OCEAN

### ISSUE THREAD

**Issue by arsenyjin** [oceanprotocol/OEPs#219]
Currently, SQUID library encapsulates the Ocean Protocol business logic. It's used to interact with all the components & APIs of the system and being implemented in the following packages:
`squid-py`
`squid-js`

As SQUID acts as the main gateway for developers to Ocean protocol from the developer experience point of view it might make sense to rename SQUID library to OCEAN and `squid-py`, `squid-js` and `Squid API` to `ocean-py`, `ocean-js` and `Ocean API` respectively.

**Comment by trentmc** [comment]
Obsolete in light of datatokens. Closing.
