### ISSUE TITLE
OEP-8 asset metadata: distribution support

### ISSUE THREAD

**Issue by shark8me** [oceanprotocol/OEPs#70]
The [Data on the web best practices standard](https://www.w3.org/TR/dwbp/#metadata) defines metadata required for datasets in a fairly detailed fashion.

Question for the Ocean team:

* Do Ocean assets support [distributions](https://www.w3.org/TR/vocab-dcat/#class-distribution)? TL;DR: A dataset could be available in multiple formats (e.g csv/xml/ttl), called distributions. Does Ocean expect that each distribution has to registered as a separate asset
* If distributions (per asset) are supported, then the metadata should support a list of distributions, each one specifying license/media-type etc.

**Comment by aaitor** [comment]
Ocean Assets don't support distributions in the next version. This could be discussed as part of future releases.
