### ISSUE TITLE
OEP-8 asset metadata : support for structured markup

### ISSUE THREAD

**Issue by shark8me** [oceanprotocol/OEPs#71]
Machine readable dataset descriptions in the form of JSON-LD or ttl would be useful because:

-  search engines such as Google can parse[ structured markup](https://developers.google.com/search/docs/data-types/dataset#example)
- mandated by standards such as [DCAT](https://www.w3.org/TR/vocab-dcat/) (and thus parse-able by data catalog/data publishing tools such as CKAN)

**Comment by kremalicious** [comment]
part of OEP-8
