### ISSUE TITLE
DID:ocean  method name (OEP-7)

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/OEPs#81]
From the DID/DDO spec:

    Since the method name is part of the DID, it SHOULD be as short as practical. A method name of five 
    characters or less is RECOMMENDED. The method name MAY reflect the name of the distributed ledger or network to which the DID method specification applies.

I think when they say short as practical, it probably means do not use ```did:oceanprotocol:````

Is there any reason to use ```ocean``` instead of ```ocn``` for  the method name:

so in Ocean the DID looks:
```
did:ocean:21tDAKCERh95uGgKbJNHYp
```
Or if we are in Marketing, the answer will be to support both method names :)

**Comment by dgossen** [comment]
OCN is already taken as a token/coin name by another project, so shouldn't be used as an acronym. It's used internally, but shouldn't be promoted externally.

**Comment by billbsing** [comment]
So if it's OCEAN then, we should change any code/tests to use this?

**Comment by aaitor** [comment]
"did:ocean:" is 10 bytes, I would use something shorter:

- did:ozn:
- did:sea:
- did:oce:

BTW, If OCN is taken, do we have an "official" Ocean ticker?

**Comment by aaitor** [comment]
I spoke with @dgossen and suggested to use **opf** ticker, that stands for Ocean Protocol Foundation, so:
`did:opf:21tDAKCERh95uGgKbJNHYp`

**Comment by aaitor** [comment]
@dgossen , looks the OP ticker is also free. You prefer OPF? or OP?

**Comment by dgossen** [comment]
"OP" is fine. Short and sweet.

The ticker for the token will be decided upon at a later date. Regardless, it should be decoupled from the network components imo.

**Comment by aaitor** [comment]
Thanks, in that case of DID we will use the schema `did:op:21tDAKCERh95uGgKbJNHYp999` of 32 ASCII characters long.

**Comment by mikera** [comment]
OP is also gamer slang for "Over-Powered". I like it :-)
